openapi: '3.0.2'
info:
  title: API для лабораторных по микропроектированию
  version: '1.0'

tags:
  - name: Аутентификация пользователя
    description: Метод аутентификации пользователей
  - name: Восстановление пароля
    description: Методы сценария восстановления пароля пользователя
  - name: Выход из системы
    description: Метод выхода из системы
  - name: Регистрация в системе
    description: Метод регистрации пользователя в системе

paths:
  /log-in:
    $ref: "paths/log_in.yml"
  /log-out:
    $ref: "paths/log_out.yml"
  /sign-up:
    $ref: "sign_up.yml"
  /send-password-recovery-letter:
    $ref: "paths/send_password_recovery_letter.yml"
  /check-password-recovery-token:
    $ref: "paths/check_password_recovery_token.yml"
  /change-password:
    $ref: "paths/change_password.yml"

components:
  securitySchemes:
    $ref: "security/jwt.yml"
